# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-amd" ];

	# Disable PSR & Panel Replay https://community.frame.work/t/screen-flickering-on-linux-kernel-6-12/62632/17
	boot.kernelParams = [ "amdgpu.dcdebugmaxk=0x410" ];

	boot.extraModulePackages = [ ];
	boot.supportedFilesystems = [ "btrfs" "ntfs" ];

	fileSystems."/" =
		{ device = "/dev/disk/by-uuid/82547ed8-b91d-45f7-9148-92881e1a2b3c";
			fsType = "btrfs";
			options = [ "compress=zstd" "relatime" "ssd" "discard=async" "space_cache=v2" "subvol=@Nixos" ];
		};

	fileSystems."/boot" =
		{ device = "/dev/disk/by-uuid/E095-0690";
			fsType = "vfat";
			options = [ "fmask=0022" "dmask=0022" ];
		};

	fileSystems."/nix" =
		{ device = "/dev/disk/by-uuid/82547ed8-b91d-45f7-9148-92881e1a2b3c";
			fsType = "btrfs";
			options = [ "noatime" "ssd" "discard=async" "space_cache=v2" "subvol=@nix" ];
		};

	fileSystems."/home" =
		{ device = "/dev/disk/by-uuid/82547ed8-b91d-45f7-9148-92881e1a2b3c";
			fsType = "btrfs";
			options = [ "compress=zstd" "relatime" "ssd" "discard=async" "space_cache=v2" "subvol=@home" ];
		};

	fileSystems."/mnt/data" =
		{ device = "/dev/disk/by-uuid/380ccf23-4345-4661-8dc7-da401ee1c9db";
			fsType = "btrfs";
			options = [ "compress=zstd" "relatime" "ssd" "discard=async" "space_cache=v2" "subvol=@data" ];
		};

	fileSystems."/mnt/games" =
		{ device = "/dev/disk/by-uuid/51f3949e-c1b6-47f0-92ee-bb114c71eb8f";
			fsType = "ext4";
		};

	fileSystems."/mnt/windows" =
		{ device = "/dev/disk/by-uuid/A2401DC0401D9C5B";
			fsType = "ntfs";
		};

	swapDevices =
		[ {
				device = "/dev/disk/by-uuid/c60d0c53-9081-4085-b917-11df0e4383cd";
				options = [ "noatime" ];
		} ];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
